KanbanProjectMvc/Models/POCOs/KanbanBoard.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using KanbanProjectMvc.Models.POCOs;

namespace KanbanProjectMvc.Models
{
    public class KanbanBoard
    {
        public int KanbanBoardId { get; set; }
        [Required]
        [Display(Name = "Board Name")]
        public string BoardName { get; set; }
        public virtual ICollection<BoardColumn> Columns { get; set; }
        
    }
}

KanbanProjectMvc/Controllers/BoardColumnsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KanbanProjectMvc.EF;
using KanbanProjectMvc.Models;

namespace KanbanProjectMvc.Controllers
{
    public class BoardColumnsController : Controller
    {
        private KanbanDbContext db = new KanbanDbContext();

        // GET: BoardColumns
        public ActionResult Index()
        {
            return View(db.Columns.ToList());
        }

        // GET: BoardColumns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardColumn boardColumn = db.Columns.Find(id);
            if (boardColumn == null)
            {
                return HttpNotFound();
            }
            return View(boardColumn);
        }

        // GET: BoardColumns/Create
        public ActionResult Create(int? boardId)
        {
            ViewBag.BoardId = boardId;
            ViewBag.BoardName = db.Boards.Find(boardId).BoardName;
            return View();
        }

        // POST: BoardColumns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BoardColumnId,ColumnName")] BoardColumn boardColumn, int? boardId)
        {
            if (ModelState.IsValid)
            {
                db.Boards.Find(boardId).Columns.Add(boardColumn);
                db.SaveChanges();
                return RedirectToAction("Details", "KanbanBoards", new { id = boardId });
            }

            return View(boardColumn);
        }

        // GET: BoardColumns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardColumn boardColumn = db.Columns.Find(id);
            if (boardColumn == null)
            {
                return HttpNotFound();
            }
            return View(boardColumn);
        }

        // POST: BoardColumns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BoardColumnId,ColumnName")] BoardColumn boardColumn)
        {
            if (ModelState.IsValid)
            {
                db.Entry(boardColumn).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(boardColumn);
        }

        // GET: BoardColumns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardColumn boardColumn = db.Columns.Find(id);
            if (boardColumn == null)
            {
                return HttpNotFound();
            }
            return View(boardColumn);
        }

        // POST: BoardColumns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BoardColumn boardColumn = db.Columns.Find(id);
            db.Columns.Remove(boardColumn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KanbanProjectMvc/Controllers/BoardStickersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KanbanProjectMvc.EF;
using KanbanProjectMvc.Models;

namespace KanbanProjectMvc.Controllers
{
    public class BoardStickersController : Controller
    {
        private KanbanDbContext db = new KanbanDbContext();

        // GET: BoardStickers
        public ActionResult Index()
        {
            return View(db.Stickers.ToList());
        }

        // GET: BoardStickers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardSticker boardSticker = db.Stickers.Find(id);
            if (boardSticker == null)
            {
                return HttpNotFound();
            }
            return View(boardSticker);
        }

        // GET: BoardStickers/Create
        public ActionResult Create(int? columnId, int? boardId)
        {
            ViewBag.ColumnId = columnId;
            ViewBag.ColumnName = db.Columns.Find(columnId).ColumnName;
            return View();
        }

        // POST: BoardStickers/MoveSticker
        [HttpPost]
        public void MoveSticker(int? id, int? toColumnId, int? boardId)
        {
            var sticker = db.Stickers.Find(id);
            var columns = db.Columns.Select(c => c).Include(c => c.Stickers).ToList();
            var fromColumn = columns.Where(c => c.Stickers.Contains(sticker)).Select(c => c).ToList().Single();
            var toColumn = columns.Where(column => column.BoardColumnId == toColumnId).ToList().Single();
            var boardUsed = db.Boards.Find(boardId);

            fromColumn.Stickers.Remove(sticker);
            toColumn.Stickers.Add(sticker);
            db.SaveChanges();
        }

        // GET: BoardStickers/MoveSticker
        //public int GetBoardId(int? id)
        //{
            
        //}

        // POST: BoardStickers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BoardStickerId,StickerName")] BoardSticker boardSticker, int? columnId, int? boardId)
        {
            if (ModelState.IsValid)
            {
                db.Columns.Find(columnId).Stickers.Add(boardSticker);
                db.SaveChanges();
                return RedirectToAction("Details", "KanbanBoards", new {id = boardId});
            }

            return View(boardSticker);
        }

        // GET: BoardStickers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardSticker boardSticker = db.Stickers.Find(id);
            if (boardSticker == null)
            {
                return HttpNotFound();
            }
            return View(boardSticker);
        }

        // POST: BoardStickers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BoardStickerId,StickerName")] BoardSticker boardSticker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(boardSticker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(boardSticker);
        }

        // GET: BoardStickers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardSticker boardSticker = db.Stickers.Find(id);
            if (boardSticker == null)
            {
                return HttpNotFound();
            }
            return View(boardSticker);
        }

        // POST: BoardStickers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BoardSticker boardSticker = db.Stickers.Find(id);
            var boardId = GetBoardId(boardSticker);
            db.Stickers.Remove(boardSticker);
            db.SaveChanges();
            return RedirectToAction("Details", "KanbanBoards", new {id = boardId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public int GetBoardId(BoardSticker sticker)
        {
            var allColumns = db.Columns.ToList();
            var stickerColumn = allColumns.Where(column => column.Stickers.Contains(sticker)).ToList().Single();

            var allBoards = db.Boards.ToList();
            var columnBoard = allBoards.Where(board => board.Columns.Contains(stickerColumn)).ToList().Single();

            return columnBoard.KanbanBoardId;
         }
    }
}

KanbanProjectMvc/Controllers/KanbanBoardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KanbanProjectMvc.EF;
using KanbanProjectMvc.Models;

namespace KanbanProjectMvc.Controllers
{
    public class KanbanBoardsController : Controller
    {
        private KanbanDbContext db = new KanbanDbContext();

        // GET: KanbanBoards
        public ActionResult Index()
        {
            return View(db.Boards.ToList());
        }

        // GET: KanbanBoards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.Boards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KanbanBoards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KanbanBoardId,BoardName")] KanbanBoard kanbanBoard)
        {
            if (ModelState.IsValid)
            {
                db.Boards.Add(kanbanBoard);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.Boards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // POST: KanbanBoards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KanbanBoardId,BoardName")] KanbanBoard kanbanBoard)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kanbanBoard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.Boards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // POST: KanbanBoards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KanbanBoard kanbanBoard = db.Boards.Find(id);
            db.Boards.Remove(kanbanBoard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KanbanProjectMvc/Views/KanbanBoards/Create.cshtml
@model KanbanProjectMvc.Models.KanbanBoard

@{
    ViewBag.Title = "Create KanbanBoard";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KanbanBoard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BoardName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BoardName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BoardName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KanbanProjectMvc/Views/KanbanBoards/Delete.cshtml
@model KanbanProjectMvc.Models.KanbanBoard

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete board '@Model.BoardName'</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BoardName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BoardName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KanbanProjectMvc/Views/KanbanBoards/Details.cshtml
@model KanbanProjectMvc.Models.KanbanBoard

@{
    ViewBag.Title = "Details";
}

<h2>@Model.BoardName</h2>
<style>
    table, th, td {
        border: 1px solid black;
        padding: 5px;
    }

    table { border-spacing: 15px; }
</style>
<script language="javascript" type="text/javascript">
    $(document).ready(function() {

        for (var i = 0; i < @(Model.Columns.Count); i++) {
            $('#droppableColumns' + i + ' img').css({ 'z-index': 10 }).draggable({
                'opacity': '0.5',
                'revert': true,
                'cursor': 'pointer'
            });
        }

        for (var i = 0; i < @(Model.Columns.Count); i++) {

            $('#droppableColumns' + i).droppable({
                drop: function(event, ui) {
                    var stickerId = $(ui.draggable).siblings('.stickerId').val();
                    var droppableId = $(this).attr("att");
                    $.ajax({
                        type: 'POST',
                        url: '/BoardStickers/MoveSticker/',
                        data: {
                            id: stickerId,
                            toColumnId: droppableId,
                            boardId: @Model.KanbanBoardId,
                        },
                        success: function(data) {
                            location.reload();
                        }
                    });
                }
            });
        }
    });
</script>


@Html.ActionLink("Add column", "Create", "BoardColumns", new {boardId = Model.KanbanBoardId}, null)
<table >
    @for (var i = 0; i < Model.Columns.Count; i++)
    {
        <tr>
            <th>@Model.Columns.ToList()[i].ColumnName</th>
        </tr>
        <tr id="droppableColumns@(i)" att="@Model.Columns.ToList()[i].BoardColumnId" style="height: 50px; width: 100px;">
            @foreach (var sticker in @Model.Columns.ToList()[i].Stickers)
            {
                <td>
                    <div>
                        <img alt="@sticker.StickerName">
                        <input type="hidden" class="stickerId" value="@sticker.BoardStickerId"/>
                        @Html.ActionLink("Delete", "Delete", "BoardStickers", new {id = sticker.BoardStickerId}, null)
                    </div>
                </td>
            }
            <td>@Html.ActionLink("Add sticker", "Create", "BoardStickers", new { columnId = Model.Columns.ToList()[i].BoardColumnId, boardId = Model.KanbanBoardId }, null)</td>
        </tr>
        
    }
</table>

KanbanProjectMvc/Views/KanbanBoards/Edit.cshtml
@model KanbanProjectMvc.Models.KanbanBoard

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KanbanBoard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.KanbanBoardId)

        <div class="form-group">
            @Html.LabelFor(model => model.BoardName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BoardName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BoardName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
        @Html.ActionLink("Add Column", "Create", "BoardColumns", new {boardId = @Model.KanbanBoardId},null)
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KanbanProjectMvc/Views/KanbanBoards/Index.cshtml
@model IEnumerable<KanbanProjectMvc.Models.KanbanBoard>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BoardName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Columns)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BoardName)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {id = item.KanbanBoardId}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.KanbanBoardId})
            </td>
        </tr>
    }

</table>